### ISSUE TITLE
Issue Getting Custom Colors to Work

### ISSUE THREAD

**Issue by ghost** [Lachee/raylib-goplus#18]
Not sure if this is a bug or I am not doing it correctly however apart from the predefined colors raylib also seems to offer the ability to define your own colors using RGBA values.

I am however really struggling to get this to work. If you take a look at the images or text below.

I create the color using the code

`	// colors
	green2 = rl.Color{77, 255, 77, 1}`

which seems to work fine however Visual Studio Code gives me a WARNING (not error) 

`github.com/lachee/raylib-goplus/raylib.Color composite literal uses unkeyed fields`

However it allows me to compile the code the problem is that though the program runs the color is blank and does not display, what is supposed to be green is just blank with no color at all.

If you have any help/advice as to how to create/use custom colors it would be really appreciated.

Nicholas

![Annotation 2020-08-18 081729](https://user-images.githubusercontent.com/65644353/90477236-54286c00-e12b-11ea-8994-ecbc4c97b8de.png)
![2](https://user-images.githubusercontent.com/65644353/90477239-55f22f80-e12b-11ea-9614-b0555155814f.png)

**Comment by Lachee** [comment]
Hello,
That is a _REALL_ dumb linter error with go. I have had this on several other projects and can be mostly ignored. There are solutions to disable it, but i am not sure what they are since it was an issue long ago.

The basic issue is that Go thinks you should be using the constructor instead of defining it as a literal (the Color{ ... } part). What you should be using isntead is `rl.NewColor(77, 255, 77, 1)`

**Comment by ghost** [comment]
Hi, thanks for getting back to me so quickly. That is still not working, the color is still blank, not sure if I am doing something wrong, the code compiles and runs perfectly with no errors or warnings however the color is still not displaying, I tried 2 versions of code see below and neither works

`		green1 := rl.NewColor(77, 255, 77, 1)
		for a := 0; a < playerhp; a++ {
			rl.DrawRectangle(51+xchange, monh-59, 3, 28, rl.Color(green1))
			xchange += 3
		}`

as well as this one 

`		green1 := rl.NewColor(77, 255, 77, 1)
		for a := 0; a < playerhp; a++ {
			rl.DrawRectangle(51+xchange, monh-59, 3, 28, green1)
			xchange += 3
		}`

Whilst they both compile and run neither of them displays the color. This might also be an issue with Raylib itself I am not sure, perhaps you are correct and there is an underlying error in the Raylib library, which is another possibility why it is not working,


![Annotation 2020-08-18 102434](https://user-images.githubusercontent.com/65644353/90489519-ab373c80-e13d-11ea-8020-721e11647a3b.png)
![2](https://user-images.githubusercontent.com/65644353/90489530-ad010000-e13d-11ea-88df-e9268eb17f00.png)

**Comment by ghost** [comment]
If you have any ideas as to how to get it working it would be great.

**Comment by Lachee** [comment]
well you have set both their alpha to 1. Try setting it to 255

**Comment by ghost** [comment]
Thanks, that worked just changed to 255 and it works perfectly, appreciate it. I am assuming that Alpha is the fade so 1 is invisible and 255 is full color is that correct?

**Comment by Lachee** [comment]
Yup,
well actually 0 will be fully transparent but that is correct.
